import { TalentData } from "../util/types";

export const data: TalentData = {
  Balance: {
    name: "Balance",
    background: "/talents/tree-backgrounds/druid/balance.jpg",
    icon: "/talents/icons/druid/balance.jpg",
    talents: {
      "Improved Wrath": {
        id: 16814,
        name: "Improved Wrath",
        position: "a1",
        icon: "/talents/icons/druid/spell_nature_abolishmagic.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Nature's Grasp": {
        id: 16689,
        name: "Nature's Grasp",
        position: "a2",
        icon: "/talents/icons/druid/spell_nature_natureswrath.jpg",
        maxRank: 1,
        reqPoints: 0,
      },
      "Improved Nature's Grasp": {
        id: 17245,
        name: "Improved Nature's Grasp",
        position: "a3",
        icon: "/talents/icons/druid/spell_nature_natureswrath.jpg",
        maxRank: 4,
        reqPoints: 0,
        arrows: [{ dir: "right", from: "a2", to: "a3" }],
      },
      "Improved Entangling Roots": {
        id: 16918,
        name: "Improved Entangling Roots",
        position: "b1",
        icon: "/talents/icons/druid/spell_nature_stranglevines.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Improved Moonfire": {
        id: 16821,
        name: "Improved Moonfire",
        position: "b2",
        icon: "/talents/icons/druid/spell_nature_starfall.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Natural Weapons": {
        id: 16902,
        name: "Natural Weapons",
        position: "b3",
        icon: "/talents/icons/druid/inv_staff_01.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Natural Shapeshifter": {
        id: 16833,
        name: "Natural Shapeshifter",
        position: "b4",
        icon: "/talents/icons/druid/spell_nature_wispsplode.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Improved Thorns": {
        id: 16836,
        name: "Improved Thorns",
        position: "c1",
        icon: "/talents/icons/druid/spell_nature_thorns.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Omen of Clarity": {
        id: 16864,
        name: "Omen of Clarity",
        position: "c3",
        icon: "/talents/icons/druid/spell_nature_crystalball.jpg",
        maxRank: 1,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "b3", to: "c3" }],
      },
      "Nature's Reach": {
        id: 16819,
        name: "Nature's Reach",
        position: "c4",
        icon: "/talents/icons/druid/spell_nature_naturetouchgrow.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      Vengeance: {
        id: 16909,
        name: "Vengeance",
        position: "d2",
        icon: "/talents/icons/druid/spell_nature_purge.jpg",
        maxRank: 5,
        reqPoints: 15,
        arrows: [{ dir: "down", from: "b2", to: "d2" }],
      },
      "Improved Starfire": {
        id: 16850,
        name: "Improved Starfire",
        position: "d3",
        icon: "/talents/icons/druid/spell_arcane_starfire.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Nature's Grace": {
        id: 16880,
        name: "Nature's Grace",
        position: "e2",
        icon: "/talents/icons/druid/spell_nature_naturesblessing.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      Moonglow: {
        id: 16845,
        name: "Moonglow",
        position: "e3",
        icon: "/talents/icons/druid/spell_nature_sentinal.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      Moonfury: {
        id: 16896,
        name: "Moonfury",
        position: "f2",
        icon: "/talents/icons/druid/spell_nature_moonglow.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
      },
      "Moonkin Form": {
        id: 24858,
        name: "Moonkin Form",
        position: "g2",
        icon: "/talents/icons/druid/spell_nature_forceofnature.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
  "Feral Combat": {
    name: "Feral Combat",
    background: "/talents/tree-backgrounds/druid/feral.jpg",
    icon: "/talents/icons/druid/feral.jpg",
    talents: {
      Ferocity: {
        id: 16934,
        name: "Ferocity",
        position: "a2",
        icon: "/talents/icons/druid/ability_hunter_pet_hyena.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Feral Aggression": {
        id: 16858,
        name: "Feral Aggression",
        position: "a3",
        icon: "/talents/icons/druid/ability_druid_demoralizingroar.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Feral Instinct": {
        id: 16947,
        name: "Feral Instinct",
        position: "b1",
        icon: "/talents/icons/druid/ability_ambush.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Brutal Impact": {
        id: 16940,
        name: "Brutal Impact",
        position: "b2",
        icon: "/talents/icons/druid/ability_druid_bash.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Thick Hide": {
        id: 16929,
        name: "Thick Hide",
        position: "b3",
        icon: "/talents/icons/druid/inv_misc_pelt_bear_03.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Feline Swiftness": {
        id: 17002,
        name: "Feline Swiftness",
        position: "c1",
        icon: "/talents/icons/druid/spell_nature_spiritwolf.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Feral Charge": {
        id: 16979,
        name: "Feral Charge",
        position: "c2",
        icon: "/talents/icons/druid/ability_hunter_pet_bear.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Sharpened Claws": {
        id: 16942,
        name: "Sharpened Claws",
        position: "c3",
        icon: "/talents/icons/druid/inv_misc_monsterclaw_04.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Improved Shred": {
        id: 16966,
        name: "Improved Shred",
        position: "d1",
        icon: "/talents/icons/druid/spell_shadow_vampiricaura.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Predatory Strikes": {
        id: 16972,
        name: "Predatory Strikes",
        position: "d2",
        icon: "/talents/icons/druid/ability_hunter_pet_cat.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Blood Frenzy": {
        id: 16952,
        name: "Blood Frenzy",
        position: "d3",
        icon: "/talents/icons/druid/ability_ghoulfrenzy.jpg",
        maxRank: 2,
        reqPoints: 15,
        arrows: [{ dir: "down", from: "c3", to: "d3" }],
      },
      "Primal Fury": {
        id: 16958,
        name: "Primal Fury",
        position: "d4",
        icon: "/talents/icons/druid/ability_racial_cannibalize.jpg",
        maxRank: 2,
        reqPoints: 15,
        arrows: [
          { dir: "right-down", from: "c3", to: "c4" },
          { dir: "right-down-down", from: "c4", to: "d4" },
        ],
      },
      "Savage Fury": {
        id: 16998,
        name: "Savage Fury",
        position: "e1",
        icon: "/talents/icons/druid/ability_druid_ravage.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "Faerie Fire (Feral)": {
        id: 16857,
        name: "Faerie Fire (Feral)",
        position: "e3",
        icon: "/talents/icons/druid/spell_nature_faeriefire.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Heart of the Wild": {
        id: 17003,
        name: "Heart of the Wild",
        position: "f2",
        icon: "/talents/icons/druid/spell_holy_blessingofagility.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "d2", to: "f2" }],
      },
      "Leader of the Pack": {
        id: 17007,
        name: "Leader of the Pack",
        position: "g2",
        icon: "/talents/icons/druid/spell_nature_unyeildingstamina.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
  Restoration: {
    name: "Restoration",
    background: "/talents/tree-backgrounds/druid/restoration.jpg",
    icon: "/talents/icons/druid/spell_nature_healingtouch.jpg",
    talents: {
      "Improved Mark of the Wild": {
        id: 17050,
        name: "Improved Mark of the Wild",
        position: "a2",
        icon: "/talents/icons/druid/spell_nature_regeneration.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Furor: {
        name: "Furor",
        position: "a3",
        icon: icons["spell_nature_unyeildingstamina"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives you ${[
          20, 40, 60, 80, 100,
        ]}% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.`,
      },
      "Improved Healing Touch": {
        name: "Improved Healing Touch",
        position: "b1",
        icon: icons["spell_nature_healingtouch"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the cast time of your Healing Touch spell by ${[
          0.1, 0.2, 0.3, 0.4, 0.5,
        ]} sec.`,
      },
      "Nature's Focus": {
        name: "Nature's Focus",
        position: "b2",
        icon: icons["spell_nature_healingwavegreater"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          14, 28, 42, 56, 70,
        ]}% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.`,
      },
      "Improved Enrage": {
        name: "Improved Enrage",
        position: "b3",
        icon: icons["ability_druid_enrage"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`The Enrage ability now instantly generates ${[
          5, 10,
        ]} Rage.`,
      },
      Reflection: {
        name: "Reflection",
        position: "c2",
        icon: icons["spell_frost_windwalkon"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Allows ${[
          5, 10, 15,
        ]}% of your Mana regeneration to continue while casting.`,
      },
      "Insect Swarm": {
        name: "Insect Swarm",
        position: "c3",
        icon: icons["spell_nature_insectswarm"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`The enemy is swarmed by insects, decreasing their chance to hit by 2% and causing 66 Nature damage over 12 sec.`,
      },
      Subtlety: {
        name: "Subtlety",
        position: "c4",
        icon: icons["ability_eyeoftheowl"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Reduces the threat generated by your Healing spells by ${[
          4, 8, 12, 16, 20,
        ]}%.`,
      },
      "Tranquil Spirit": {
        name: "Tranquil Spirit",
        position: "d2",
        icon: icons["spell_holy_elunesgrace"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Reduces the mana cost of your Healing Touch and Tranquility spells by ${[
          2, 4, 6, 8, 10,
        ]}%.`,
      },
      "Improved Rejuvenation": {
        name: "Improved Rejuvenation",
        position: "d4",
        icon: icons["spell_nature_rejuvenation"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the effect of your Rejuvenation spell by ${[
          5, 10, 15,
        ]}%.`,
      },
      "Nature's Swiftness": {
        name: "Nature's Swiftness",
        position: "e1",
        icon: icons["spell_nature_ravenform"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Improved Healing Touch",
        arrows: [{ dir: "down", from: "b1", to: "e1" }],
        description: talentText`When activated, your next Nature spell becomes an instant cast spell.`,
      },
      "Gift of Nature": {
        name: "Gift of Nature",
        position: "e3",
        icon: icons["spell_nature_protectionformnature"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Insect Swarm",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`Increases the effect of all healing spells by ${[
          2, 4, 6, 8, 10,
        ]}%.`,
      },
      "Improved Tranquility": {
        name: "Improved Tranquility",
        position: "e4",
        icon: icons["spell_nature_tranquility"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Reduces the threat caused by Tranquility by ${[
          50, 100,
        ]}%.`,
      },
      "Improved Regrowth": {
        name: "Improved Regrowth",
        position: "f3",
        icon: icons["spell_nature_resistnature"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the critical effect chance of your Regrowth spell by ${[
          10, 20, 30, 40, 50,
        ]}%.`,
      },
      Swiftmend: {
        name: "Swiftmend",
        position: "g2",
        icon: icons["inv_relics_idolofrejuvenation"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Tranquil Spirit",
        arrows: [{ dir: "down", from: "d2", to: "g2" }],
        description: talentText`Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.`,
      },
    },
  },
};
