import { TalentData } from "../util/types";

export const data: TalentData = {
  Elemental: {
    name: "Elemental",
    background: "/talents/tree-backgrounds/shaman/elemental.jpg",
    icon: "/talents/icons/shaman/spell_nature_lightning.jpg",
    talents: {
      Convection: {
        id: 16039,
        name: "Convection",
        position: "a2",
        icon: "/talents/icons/shaman/spell_nature_wispsplode.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Concussion: {
        id: 16035,
        name: "Concussion",
        position: "a3",
        icon: "/talents/icons/shaman/spell_fire_fireball.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Earth's Grasp": {
        id: 16043,
        name: "Earth's Grasp",
        position: "b1",
        icon: "/talents/icons/shaman/spell_nature_stoneclawtotem.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Elemental Warding": {
        id: 28996,
        name: "Elemental Warding",
        position: "b2",
        icon: "/talents/icons/shaman/spell_nature_spiritarmor.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Call of Flame": {
        id: 16038,
        name: "Call of Flame",
        position: "b3",
        icon: "/talents/icons/shaman/spell_fire_immolation.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Elemental Focus": {
        id: 16164,
        name: "Elemental Focus",
        position: "c1",
        icon: "/talents/icons/shaman/spell_shadow_manaburn.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      Reverberation: {
        id: 16040,
        name: "Reverberation",
        position: "c2",
        icon: "/talents/icons/shaman/spell_frost_frostward.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Call of Thunder": {
        id: 16041,
        name: "Call of Thunder",
        position: "c3",
        icon: "/talents/icons/shaman/spell_nature_callstorm.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Improved Fire Totems": {
        id: 16086,
        name: "Improved Fire Totems",
        position: "d1",
        icon: "/talents/icons/shaman/spell_fire_sealoffire.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Eye of the Storm": {
        id: 29062,
        name: "Eye of the Storm",
        position: "d2",
        icon: "/talents/icons/shaman/spell_nature_eyeofthestorm.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Elemental Devastation": {
        id: 30160,
        name: "Elemental Devastation",
        position: "d4",
        icon: "/talents/icons/shaman/classic_spell_fire_elementaldevastation.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Storm Reach": {
        id: 28999,
        name: "Storm Reach",
        position: "e1",
        icon: "/talents/icons/shaman/spell_nature_stormreach.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "Elemental Fury": {
        id: 16166,
        name: "Elemental Fury",
        position: "e2",
        icon: "/talents/icons/shaman/spell_fire_volcano.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Lightning Mastery": {
        id: 16578,
        name: "Lightning Mastery",
        position: "f3",
        icon: "/talents/icons/shaman/spell_nature_lightning.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "c3", to: "f3" }],
      },
      "Elemental Mastery": {
        id: 16166,
        name: "Elemental Mastery",
        position: "g2",
        icon: "/talents/icons/shaman/spell_nature_wispheal.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Enhancement: {
    name: "Enhancement",
    background: "/talents/tree-backgrounds/shaman/enhancement.jpg",
    icon: "/talents/icons/shaman/spell_nature_lightningshield.jpg",
    talents: {
      "Ancestral Knowledge": {
        id: 17485,
        name: "Ancestral Knowledge",
        position: "a2",
        icon: "/talents/icons/shaman/spell_shadow_grimward.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Sheild Specialization": {
        id: 16253,
        name: "Sheild Specialization",
        position: "a3",
        icon: "/talents/icons/shaman/inv_shield_06.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Guardian Totems": {
        id: 16258,
        name: "Guardian Totems",
        position: "b1",
        icon: "/talents/icons/shaman/spell_nature_stoneskintotem.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Thundering Strikes": {
        id: 16255,
        name: "Thundering Strikes",
        position: "b2",
        icon: "/talents/icons/shaman/ability_thunderbolt.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Improved Ghost Wolf": {
        id: 16262,
        name: "Improved Ghost Wolf",
        position: "b3",
        icon: "/talents/icons/shaman/spell_nature_spiritwolf.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Lightning Shield": {
        id: 16261,
        name: "Improved Lightning Shield",
        position: "b4",
        icon: "/talents/icons/shaman/spell_nature_lightningshield.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Enhancing Totems": {
        id: 16259,
        name: "Enhancing Totems",
        position: "c1",
        icon: "/talents/icons/shaman/spell_nature_earthbindtotem.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Two-Handed Axes and Maces": {
        id: 16269,
        name: "Two-Handed Axes and Maces",
        position: "c3",
        icon: "/talents/icons/shaman/inv_axe_10.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      Anticipation: {
        id: 16254,
        name: "Anticipation",
        position: "c4",
        icon: "/talents/icons/shaman/spell_nature_mirrorimage.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      Flurry: {
        id: 16256,
        name: "Flurry",
        position: "d2",
        icon: "/talents/icons/shaman/ability_ghoulfrenzy.jpg",
        maxRank: 5,
        reqPoints: 15,
        arrows: [{ dir: "down", from: "b2", to: "d2" }],
      },
      Toughnes: {
        id: 16252,
        name: "Toughness",
        position: "d3",
        icon: "/talents/icons/shaman/spell_holy_devotion.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Improved Weapon Totems": {
        id: 29192,
        name: "Improved Weapon Totems",
        position: "e1",
        icon: "/talents/icons/shaman/spell_fire_enchantweapon.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "Elemental Weapons": {
        id: 16266,
        name: "Elemental Weapons",
        position: "e2",
        icon: "/talents/icons/shaman/spell_fire_flametounge.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      Parry: {
        id: 16268,
        name: "Parry",
        position: "e3",
        icon: "/talents/icons/shaman/ability_parry.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Weapon Mastery": {
        id: 29082,
        name: "Weapon Mastery",
        position: "f3",
        icon: "/talents/icons/shaman/ability_hunter_swiftstrike.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      Stormstrike: {
        id: 17364,
        name: "Stormstrike",
        position: "g2",
        icon: "/talents/icons/shaman/spell_holy_sealofmight.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Restoration: {
    name: "Restoration",
    background: "/talents/tree-backgrounds/shaman/restoration.jpg",
    icon: "/talents/icons/shaman/spell_nature_magicimmunity.jpg",
    talents: {
      "Improved Healing Wave": {
        id: 16182,
        name: "Improved Healing Wave",
        position: "a2",
        icon: "/talents/icons/shaman/spell_nature_magicimmunity.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Tidal Focus": {
        id: 16179,
        name: "Tidal Focus",
        position: "a3",
        icon: "/talents/icons/shaman/spell_frost_manarecharge.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Imroved Reincarnation": {
        id: 16184,
        name: "Imroved Reincarnation",
        position: "b1",
        icon: "/talents/icons/shaman/spell_nature_reincarnation.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Ancestral Healing": {
        id: 16176,
        name: "Ancestral Healing",
        position: "b2",
        icon: "/talents/icons/shaman/spell_nature_undyingstrength.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Totemic Focus": {
        id: 16173,
        name: "Totemic Focus",
        position: "b3",
        icon: "/talents/icons/shaman/spell_nature_moonglow.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Nature's Guidance": {
        id: 16180,
        name: "Nature's Guidance",
        position: "c1",
        icon: "/talents/icons/shaman/spell_frost_stun.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Healing Focus": {
        id: 16181,
        name: "Healing Focus",
        position: "c2",
        icon: "/talents/icons/shaman/spell_nature_healingwavelesser.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Totemic Mastery": {
        id: 16189,
        name: "Totemic Mastery",
        position: "c3",
        icon: "/talents/icons/shaman/spell_nature_nullward.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Healing Grace": {
        id: 29187,
        name: "Healing Grace",
        position: "c4",
        icon: "/talents/icons/shaman/spell_nature_healingtouch.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Restorative Totems": {
        id: 16187,
        name: "Restorative Totems",
        position: "d2",
        icon: "/talents/icons/shaman/spell_nature_manaregentotem.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Tidal Mastery": {
        id: 16194,
        name: "Tidal Mastery",
        position: "d3",
        icon: "/talents/icons/shaman/spell_nature_tranquility.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Healing Way": {
        id: 29206,
        name: "Healing Way",
        position: "e1",
        icon: "/talents/icons/shaman/classic_spell_nature_healingway.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      "Nature's Swiftness": {
        id: 16188,
        name: "Nature's Swiftness",
        position: "e3",
        icon: "/talents/icons/shaman/spell_nature_ravenform.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      Purification: {
        id: 16178,
        name: "Purification",
        position: "f3",
        icon: "/talents/icons/shaman/spell_frost_wizardmark.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      "Mana Tide Totem": {
        id: 16190,
        name: "Mana Tide Totem",
        position: "g2",
        icon: "/talents/icons/shaman/spell_frost_summonwaterelemental.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "d2", to: "g2" }],
      },
    },
  },
};
