export const data = {
  Arms: {
    name: "Arms",
    backgorund: "/talents/tree-backgrounds/warrior/arms.jpg",
    icon: "/talents/icons/warrior/ability_rogue_eviscerate.jpg",
    talents: [
      {
        name: "Improved Heroic Strike",
        top: "8px",
        left: "8px",
        icon: "/talents/icons/warrior/ability_rogue_ambush.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      {
        name: "Deflection",
        top: "8px",
        left: "68px",
        icon: "/talents/icons/warrior/ability_parry.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      {
        name: "Improved Rend",
        top: "8px",
        left: "128px",
        icon: "/talents/icons/warrior/ability_gouge.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      {
        name: "Improved Charge",
        top: "68px",
        left: "8px",
        icon: "/talents/icons/warrior/ability_warrior_charge.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      {
        name: "Tactical Mastery",
        top: "68px",
        left: "68px",
        icon: "/talents/icons/warrior/spell_nature_enchantarmor.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      {
        name: "Improved Thunder Clap",
        top: "68px",
        left: "188px",
        icon: "/talents/icons/warrior/ability_thunderclap.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      {
        name: "Improved Overpower",
        top: "128px",
        left: "8px",
        icon: "/talents/icons/warrior/inv_sword_05.jpg",
        maxRank: 2,
        reqPoints: 2,
      },
      {
        name: "Anger Management",
        top: "128px",
        left: "68px",
        icon: "/talents/icons/warrior/spell_holy_blessingofstamina.jpg",
        maxRank: 1,
        reqPoints: 1,
      },
      {
        name: "Deep Wounds",
        top: "128px",
        left: "128px",
        icon: "/talents/icons/warrior/ability_backstab.jpg",
        maxRank: 3,
        reqPoints: 3,
      },
      {
        name: "Two-Handed Weapon Specialization",
        top: "188px",
        left: "68px",
        icon: "/talents/icons/warrior/inv_axe_09.jpg",
        maxRank: 3,
        reqPoints: 3,
      },
      {
        name: "Impale",
        top: "188px",
        left: "128px",
        icon: "/talents/icons/warrior/ability_searingarrow.jpg",
        maxRank: 2,
        reqPoints: 1,
      },
      {
        name: "Axe Specialization",
        top: "248px",
        left: "8px",
        icon: "/talents/icons/warrior/inv_axe_06.jpg",
        maxRank: 5,
        reqPoints: 1,
      },
      {
        name: "Sweeping Strikes",
        top: "248px",
        left: "68px",
        icon: "/talents/icons/warrior/ability_rogue_slicedice.jpg",
        maxRank: 1,
        reqPoints: 1,
      },
      {
        name: "Mace Specialization",
        top: "248px",
        left: "128px",
        icon: "/talents/icons/warrior/inv_mace_01.jpg",
        maxRank: 5,
        reqPoints: 1,
      },
      {
        name: "Sword Specialization",
        top: "248px",
        left: "188px",
        icon: "/talents/icons/warrior/inv_sword_27.jpg",
        maxRank: 5,
        reqPoints: 1,
      },
      {
        name: "Polearm Specialization",
        top: "308px",
        left: "8px",
        icon: "/talents/icons/warrior/inv_weapon_halbard_01.jpg",
        maxRank: 1,
        reqPoints: 1,
      },
      {
        name: "Improved Hamstring",
        top: "308px",
        left: "128px",
        icon: "/talents/icons/warrior/ability_shockwave.jpg",
        maxRank: 3,
        reqPoints: 1,
      },
      {
        name: "Mortal Strike",
        top: "368px",
        left: "68px",
        icon: "/talents/icons/warrior/ability_warrior_savageblow.jpg",
        maxRank: 1,
        reqPoints: 1,
      },
    ],
  },
};
