import { TalentData } from "../util/types";

export const data: TalentData = {
  Arms: {
    name: "Arms",
    background: "/talents/tree-backgrounds/warrior/arms.jpg",
    icon: "/talents/icons/warrior/ability_rogue_eviscerate.jpg",
    talents: {
      "Improved Heroic Strike": {
        name: "Improved Heroic Strike",
        position: "a1",
        icon: "/talents/icons/warrior/ability_rogue_ambush.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Deflection": {
        name: "Deflection",
        position: "a2",
        icon: "/talents/icons/warrior/ability_parry.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Rend": {
        name: "Improved Rend",
        position: "a3",
        icon: "/talents/icons/warrior/ability_gouge.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Improved Charge": {
        name: "Improved Charge",
        position: "b1",
        icon: "/talents/icons/warrior/ability_warrior_charge.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      "Tactical Mastery": {
        name: "Tactical Mastery",
        position: "b2",
        icon: "/talents/icons/warrior/spell_nature_enchantarmor.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Thunder Clap": {
        name: "Improved Thunder Clap",
        position: "b4",
        icon: "/talents/icons/warrior/ability_thunderclap.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Improved Overpower": {
        name: "Improved Overpower",
        position: "c1",
        icon: "/talents/icons/warrior/inv_sword_05.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      "Anger Management": {
        name: "Anger Management",
        position: "c2",
        icon: "/talents/icons/warrior/spell_holy_blessingofstamina.jpg",
        maxRank: 1,
        reqPoints: 0,
        arrows: [{ dir: "down", from: "b2", to: "c2" }],
      },
      "Deep Wounds": {
        name: "Deep Wounds",
        position: "c3",
        icon: "/talents/icons/warrior/ability_backstab.jpg",
        maxRank: 3,
        reqPoints: 0,
        arrows: [{ dir: "down", from: "a3", to: "c3" }],
      },
      "Two-Handed Weapon Specialization": {
        name: "Two-Handed Weapon Specialization",
        position: "d2",
        icon: "/talents/icons/warrior/inv_axe_09.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Impale": {
        name: "Impale",
        position: "d3",
        icon: "/talents/icons/warrior/ability_searingarrow.jpg",
        maxRank: 2,
        reqPoints: 0,
        arrows: [{ dir: "down", from: "c3", to: "d3" }],
      },
      "Axe Specialization": {
        name: "Axe Specialization",
        position: "e1",
        icon: "/talents/icons/warrior/inv_axe_06.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Sweeping Strikes": {
        name: "Sweeping Strikes",
        position: "e2",
        icon: "/talents/icons/warrior/ability_rogue_slicedice.jpg",
        maxRank: 1,
        reqPoints: 0,
      },
      "Mace Specialization": {
        name: "Mace Specialization",
        position: "e3",
        icon: "/talents/icons/warrior/inv_mace_01.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Sword Specialization": {
        name: "Sword Specialization",
        position: "e4",
        icon: "/talents/icons/warrior/inv_sword_27.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Polearm Specialization": {
        name: "Polearm Specialization",
        position: "f1",
        icon: "/talents/icons/warrior/inv_weapon_halbard_01.jpg",
        maxRank: 1,
        reqPoints: 0,
      },
      "Improved Hamstring": {
        name: "Improved Hamstring",
        position: "f3",
        icon: "/talents/icons/warrior/ability_shockwave.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Mortal Strike": {
        name: "Mortal Strike",
        position: "g2",
        icon: "/talents/icons/warrior/ability_warrior_savageblow.jpg",
        maxRank: 1,
        reqPoints: 0,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Fury: {
    name: "Fury",
    background: "/talents/tree-backgrounds/warrior/fury.jpg",
    icon: "/talents/icons/warrior/ability_warrior_innerrage.jpg",
    talents: {
      "Booming Voice": {
        name: "Booming Voice",
        position: "a2",
        icon: "/talents/icons/warrior/spell_nature_purge.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Cruelty: {
        name: "Cruelty",
        position: "a3",
        icon: "/talents/icons/warrior/ability_rogue_eviscerate.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Demoralizing Shout": {
        name: "Improved Demoralizing Shout",
        position: "b2",
        icon: "/talents/icons/warrior/ability_warrior_warcry.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Unbridled Wrath": {
        name: "Unbridled Wrath",
        position: "b3",
        icon: "/talents/icons/warrior/spell_nature_stoneclawtotem.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Improved Cleave": {
        name: "Improved Cleave",
        position: "c1",
        icon: "/talents/icons/warrior/ability_warrior_cleave.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Piercing Howl": {
        name: "Piercing Howl",
        position: "c2",
        icon: "/talents/icons/warrior/spell_shadow_deathscream.jpg",
        maxRank: 1,
        reqPoints: 0,
      },
      "Blood Craze": {
        name: "Blood Craze",
        position: "c3",
        icon: "/talents/icons/warrior/spell_shadow_summonimp.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Improved Battle Shout": {
        name: "Improved Battle Shout",
        position: "c4",
        icon: "/talents/icons/warrior/ability_warrior_battleshout.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Dual Wield Specialization": {
        name: "Dual Wield Specialization",
        position: "d1",
        icon: "/talents/icons/warrior/ability_dualwield.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Execute": {
        name: "Improved Execute",
        position: "d2",
        icon: "/talents/icons/warrior/inv_sword_48.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      Enrage: {
        name: "Enrage",
        position: "d3",
        icon: "/talents/icons/warrior/spell_shadow_unholyfrenzy.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Slam": {
        name: "Improved Slam",
        position: "e1",
        icon: "/talents/icons/warrior/ability_warrior_decisivestrike.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Death Wish": {
        name: "Death Wish",
        position: "e2",
        icon: "/talents/icons/warrior/spell_shadow_deathpact.jpg",
        maxRank: 1,
        reqPoints: 0,
      },
      "Improved Intercept": {
        name: "Improved Intercept",
        position: "e4",
        icon: "/talents/icons/warrior/ability_rogue_sprint.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      "Improved Berserker Rage": {
        name: "Improved Berserker Rage",
        position: "f1",
        icon: "/talents/icons/warrior/spell_nature_ancestralguardian.jpg",
        maxRank: 2,
        reqPoints: 25,
      },
      Flurry: {
        name: "Flurry",
        position: "f3",
        icon: "/talents/icons/warrior/ability_ghoulfrenzy.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "d3", to: "f3" }],
      },
      Bloodthirst: {
        name: "Bloodthirst",
        position: "g2",
        icon: "/talents/icons/warrior/spell_nature_bloodlust.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Protection: {
    name: "Protection",
    background: "/talents/tree-backgrounds/warrior/protection.jpg",
    icon: "/talents/icons/warrior/inv_shield_06.jpg",
    talents: {
      "Shield Specialization": {
        name: "Shield Specialization",
        position: "a2",
        icon: "/talents/icons/warrior/inv_shield_06.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Anticipation: {
        name: "Anticipation",
        position: "a3",
        icon: "/talents/icons/warrior/spell_nature_mirrorimage.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Bloodrage": {
        name: "Improved Bloodrage",
        position: "b1",
        icon: "/talents/icons/warrior/ability_racial_bloodrage.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      Toughness: {
        name: "Toughness",
        position: "b3",
        icon: "/talents/icons/warrior/spell_holy_devotion.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Iron Will": {
        name: "Iron Will",
        position: "b4",
        icon: "/talents/icons/warrior/spell_magic_magearmor.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Last Stand": {
        name: "Last Stand",
        position: "c1",
        icon: "/talents/icons/warrior/spell_holy_ashestoashes.jpg",
        maxRank: 1,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "b1", to: "c1" }],
      },
      "Improved Shield Block": {
        name: "Improved Shield Block",
        position: "c2",
        icon: "/talents/icons/warrior/ability_defend.jpg",
        maxRank: 3,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "a2", to: "c2" }],
      },
      "Improved Revenge": {
        name: "Improved Revenge",
        position: "c3",
        icon: "/talents/icons/warrior/ability_warrior_revenge.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      Defiance: {
        name: "Defiance",
        position: "c4",
        icon: "/talents/icons/warrior/ability_warrior_innerrage.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Improved Sunder Armor": {
        name: "Improved Sunder Armor",
        position: "d1",
        icon: "/talents/icons/warrior/ability_warrior_sunder.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Improved Disarm": {
        name: "Improved Disarm",
        position: "d2",
        icon: "/talents/icons/warrior/ability_warrior_disarm.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Improved Taunt": {
        name: "Improved Taunt",
        position: "d3",
        icon: "/talents/icons/warrior/spell_nature_reincarnation.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Improved Shield Wall": {
        name: "Improved Shield Wall",
        position: "e1",
        icon: "/talents/icons/warrior/ability_warrior_shieldwall.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "Concussion Blow": {
        name: "Concussion Blow",
        position: "e2",
        maxRank: 1,
        icon: "/talents/icons/warrior/ability_thunderbolt.jpg",
        reqPoints: 20,
      },
      "Improved Shield Bash": {
        name: "Improved Shield Bash",
        position: "e3",
        icon: "/talents/icons/warrior/ability_warrior_shieldbash.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "One-Handed Specialization": {
        name: "One-Handed Specialization",
        position: "f3",
        icon: "/talents/icons/warrior/inv_sword_20.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      "Shield Slam": {
        name: "Shield Slam",
        position: "g2",
        icon: "/talents/icons/warrior/inv_shield_05.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
};
