import { TalentData } from "../util/types";

export const data: TalentData = {
  Assassination: {
    name: "Assassination",
    background: "/talents/tree-backgrounds/rogue/assassination.jpg",
    icon: "/talents/icons/rogue/ability_rogue_eviscerate.jpg",
    talents: {
      "Improved Eviscerate": {
        id: 14162,
        name: "Improved Eviscerate",
        position: "a1",
        icon: "/talents/icons/rogue/ability_rogue_eviscerate.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Remorseless Attacks": {
        id: 14144,
        name: "Remorseless Attacks",
        position: "a2",
        icon: "/talents/icons/rogue/ability_fiegndead.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      Malice: {
        id: 14138,
        name: "Malice",
        position: "a3",
        icon: "/talents/icons/rogue/ability_racial_bloodrage.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Ruthlessness: {
        id: 14156,
        name: "Ruthlessness",
        position: "b1",
        icon: "/talents/icons/rogue/ability_druid_disembowel.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      Murder: {
        id: 14158,
        name: "Murder",
        position: "b2",
        icon: "/talents/icons/rogue/spell_shadow_deathscream.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Slice and Dice": {
        id: 14165,
        name: "Improved Slice and Dice",
        position: "b4",
        icon: "/talents/icons/rogue/ability_rogue_slicedice.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Relentless Strikes": {
        id: 14179,
        name: "Relentless Strikes",
        position: "c1",
        icon: "/talents/icons/rogue/ability_warrior_decisivestrike.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Improved Expositione Armor": {
        id: 14168,
        name: "Improved Expositione Armor",
        position: "c2",
        icon: "/talents/icons/rogue/ability_warrior_riposte.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      Lethality: {
        id: 14128,
        name: "Lethality",
        position: "c3",
        icon: "/talents/icons/rogue/ability_criticalstrike.jpg",
        maxRank: 5,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "a3", to: "c3" }],
      },
      "Vile Poisons": {
        id: 16513,
        name: "Vile Poisons",
        position: "d2",
        icon: "/talents/icons/rogue/ability_rogue_feigndeath.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Improved Poisons": {
        id: 14113,
        name: "Improved Poisons",
        position: "d3",
        icon: "/talents/icons/rogue/ability_poisons.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Cold Blood": {
        id: 14177,
        name: "Cold Blood",
        position: "e2",
        icon: "/talents/icons/rogue/spell_ice_lament.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Improved Kidney Shot": {
        id: 14174,
        name: "Improved Kidney Shot",
        position: "e3",
        icon: "/talents/icons/rogue/ability_rogue_kidneyshot.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      "Seal Fate": {
        id: 14186,
        name: "Seal Fate",
        position: "f2",
        icon: "/talents/icons/rogue/spell_shadow_chilltouch.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
      },
      Vigor: {
        id: 14983,
        name: "Vigor",
        position: "g2",
        icon: "/talents/icons/rogue/spell_nature_earthbindtotem.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
  Combat: {
    name: "Combat",
    background: "/talents/tree-backgrounds/rogue/combat.jpg",
    icon: "/talents/icons/rogue/ability_backstab.jpg",
    talents: {
      "Improved Gouge": {
        id: 13741,
        name: "Improved Gouge",
        position: "a1",
        icon: "/talents/icons/rogue/ability_gouge.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Improved Sinister Strike": {
        id: 13732,
        name: "Improved Sinister Strike",
        position: "a2",
        icon: "/talents/icons/rogue/spell_shadow_ritualofsacrifice.jpg",
        maxRank: 2,
        reqPoints: 0,
      },
      "Lightening Reflexes": {
        id: 13712,
        name: "Lightening Reflexes",
        position: "a3",
        icon: "/talents/icons/rogue/spell_nature_invisibilty.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Backstab": {
        id: 13733,
        name: "Improved Backstab",
        position: "b1",
        icon: "/talents/icons/rogue/ability_backstab.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      Deflection: {
        id: 13713,
        name: "Deflection",
        position: "b2",
        icon: "/talents/icons/rogue/ability_parry.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      Precision: {
        id: 13705,
        name: "Precision",
        position: "b3",
        icon: "/talents/icons/rogue/ability_marksmanship.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      Endurance: {
        id: 13742,
        name: "Endurance",
        position: "c1",
        icon: "/talents/icons/rogue/spell_shadow_shadowward.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      Ripositionte: {
        id: 14251,
        name: "Ripositionte",
        position: "c2",
        icon: "/talents/icons/rogue/ability_warrior_challange.jpg",
        maxRank: 1,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "b2", to: "c2" }],
      },
      "Improved Sprint": {
        id: 13743,
        name: "Improved Sprint",
        position: "c4",
        icon: "/talents/icons/rogue/ability_rogue_sprint.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Improved Kick": {
        id: 13754,
        name: "Improved Kick",
        position: "d1",
        icon: "/talents/icons/rogue/ability_kick.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Dagger Specialization": {
        id: 13706,
        name: "Dagger Specialization",
        position: "d2",
        icon: "/talents/icons/rogue/inv_weapon_shortblade_05.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Dual Wield Specialization": {
        id: 13715,
        name: "Dual Wield Specialization",
        position: "d3",
        icon: "/talents/icons/rogue/ability_dualwield.jpg",
        maxRank: 5,
        reqPoints: 15,
        arrows: [{ dir: "down", from: "b3", to: "d3" }],
      },
      "Mace Specialization": {
        id: 13709,
        name: "Mace Specialization",
        position: "e1",
        icon: "/talents/icons/rogue/inv_mace_01.jpg",
        maxRank: 5,
        reqPoints: 20,
      },
      "Blade Flurry": {
        id: 13877,
        name: "Blade Flurry",
        position: "e2",
        icon: "/talents/icons/rogue/ability_warrior_punishingblow.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Sword Specialization": {
        id: 13960,
        name: "Sword Specialization",
        position: "e3",
        icon: "/talents/icons/rogue/inv_sword_27.jpg",
        maxRank: 5,
        reqPoints: 20,
      },
      "Fist Weapon Specialization": {
        id: 13707,
        name: "Fist Weapon Specialization",
        position: "e4",
        icon: "/talents/icons/rogue/inv_gauntlets_04.jpg",
        maxRank: 5,
        reqPoints: 20,
      },
      "Weapon Expertise": {
        id: 30919,
        name: "Weapon Expertise",
        position: "f2",
        icon: "/talents/icons/rogue/spell_holy_blessingofstrength.jpg",
        maxRank: 2,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
      },
      Aggression: {
        id: 18427,
        name: "Aggression",
        position: "f3",
        icon: "/talents/icons/rogue/ability_racial_avatar.jpg",
        maxRank: 3,
        reqPoints: 25,
      },
      "Adrenaline Rush": {
        id: 13750,
        name: "Adrenaline Rush",
        position: "g2",
        icon: "/talents/icons/rogue/spell_shadow_shadowworddominate.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
  Subtlety: {
    name: "Subtlety",
    background: "/talents/tree-backgrounds/rogue/subtlety.jpg",
    icon: "/talents/icons/rogue/ability_stealth.jpg",
    talents: {
      "Master of Deception": {
        id: 13958,
        name: "Master of Deception",
        position: "a2",
        icon: "/talents/icons/rogue/spell_shadow_charm.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Opportunity: {
        id: 14057,
        name: "Opportunity",
        position: "a3",
        icon: "/talents/icons/rogue/ability_warrior_warcry.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Sleight of Hand": {
        id: 30892,
        name: "Sleight of Hand",
        position: "b1",
        icon: "/talents/icons/rogue/ability_rogue_feint.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      Elusiveness: {
        id: 13981,
        name: "Elusiveness",
        position: "b2",
        icon: "/talents/icons/rogue/spell_magic_lesserinvisibilty.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      Camouflage: {
        id: 13975,
        name: "Camouflage",
        position: "b3",
        icon: "/talents/icons/rogue/ability_stealth.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      Initiative: {
        id: 13976,
        name: "Initiative",
        position: "c1",
        icon: "/talents/icons/rogue/spell_shadow_fumble.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Ghostly Strike": {
        id: 14278,
        name: "Ghostly Strike",
        position: "c2",
        icon: "/talents/icons/rogue/spell_shadow_curse.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Improved Ambush": {
        id: 14079,
        name: "Improved Ambush",
        position: "c3",
        icon: "/talents/icons/rogue/ability_rogue_ambush.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      Setup: {
        id: 13983,
        name: "Setup",
        position: "d1",
        icon: "/talents/icons/rogue/spell_nature_mirrorimage.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Improved Sap": {
        id: 14076,
        name: "Improved Sap",
        position: "d2",
        icon: "/talents/icons/rogue/ability_sap.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Serrated Blades": {
        id: 14171,
        name: "Serrated Blades",
        position: "d3",
        icon: "/talents/icons/rogue/inv_sword_17.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Heightened Senses": {
        id: 30894,
        name: "Heightened Senses",
        position: "e1",
        icon: "/talents/icons/rogue/ability_ambush.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      Preparation: {
        id: 14185,
        name: "Preparation",
        position: "e2",
        icon: "/talents/icons/rogue/spell_shadow_antishadow.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Dirty Deeds": {
        id: 14082,
        name: "Dirty Deeds",
        position: "e3",
        icon: "/talents/icons/rogue/spell_shadow_summonsuccubus.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      Hemmorhage: {
        id: 15511,
        name: "Hemmorhage",
        position: "e4",
        icon: "/talents/icons/rogue/spell_shadow_lifedrain.jpg",
        maxRank: 1,
        reqPoints: 20,
        arrows: [
          { dir: "right-down", from: "d3", to: "d4" },
          { dir: "right-down-down", from: "d4", to: "e4" },
        ],
      },
      Deadliness: {
        id: 30902,
        name: "Deadliness",
        position: "f3",
        icon: "/talents/icons/rogue/inv_weapon_crossbow_11.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      Premeditation: {
        id: 14183,
        name: "Premeditation",
        position: "g2",
        icon: "/talents/icons/rogue/spell_shadow_possession.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
};
