import { TalentData } from "../util/types";

export const data: TalentData = {
  Holy: {
    name: "Holy",
    background: "/talents/tree-backgrounds/paladin/holy.jpg",
    icon: "/talents/icons/paladin/spell_holy_holybolt.jpg",
    talents: {
      "Divine Strength": {
        id: 20262,
        name: "Divine Strength",
        position: "a2",
        icon: "/talents/icons/paladin/spell_holy_auraoflight.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Divine Intellect": {
        id: 20257,
        name: "Divine Intellect",
        position: "a3",
        icon: "/talents/icons/paladin/spell_nature_sleep.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Spiritual Focus": {
        id: 20205,
        name: "Spiritual Focus",
        position: "b2",
        icon: "/talents/icons/paladin/spell_arcane_blink.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Improved Seal of Righteousness": {
        id: 20224,
        name: "Improved Seal of Righteousness",
        position: "b3",
        icon: "/talents/icons/paladin/ability_thunderbolt.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Healing Light": {
        id: 20237,
        name: "Healing Light",
        position: "c1",
        icon: "/talents/icons/paladin/spell_holy_holybolt.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      Consecration: {
        id: 26573,
        name: "Consecration",
        position: "c2",
        icon: "/talents/icons/paladin/spell_holy_innerfire.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Improved Lay on Hands": {
        id: 20234,
        name: "Improved Lay on Hands",
        position: "c3",
        icon: "/talents/icons/paladin/spell_holy_layonhands.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Unyielding Faith": {
        id: 9453,
        name: "Unyielding Faith",
        position: "c4",
        icon: "/talents/icons/paladin/spell_holy_unyieldingfaith.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      Illumination: {
        id: 20210,
        name: "Illumination",
        position: "d2",
        icon: "/talents/icons/paladin/spell_holy_greaterheal.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Improved Blessing of Wisdom": {
        id: 20244,
        name: "Improved Blessing of Wisdom",
        position: "d3",
        icon: "/talents/icons/paladin/spell_holy_sealofwisdom.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Divine Favor": {
        id: 20216,
        name: "Divine Favor",
        position: "e2",
        icon: "/talents/icons/paladin/spell_holy_heal.jpg",
        maxRank: 1,
        reqPoints: 20,
        arrows: [{ dir: "down", from: "d2", to: "e2" }],
      },
      "Lasting Judgement": {
        id: 20359,
        name: "Lasting Judgement",
        position: "e3",
        icon: "/talents/icons/paladin/spell_holy_healingaura.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      "Holy Power": {
        id: 20473,
        name: "Holy Power",
        position: "f3",
        icon: "/talents/icons/paladin/spell_holy_power.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      "Holy Shock": {
        id: 20473,
        name: "Holy Shock",
        position: "g2",
        icon: "/talents/icons/paladin/spell_holy_searinglight.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Protection: {
    name: "Protection",
    background: "/talents/tree-backgrounds/paladin/protection.jpg",
    icon: "/talents/icons/paladin/spell_holy_devotionaura.jpg",
    talents: {
      "Improved Devotion Aura": {
        id: 20138,
        name: "Improved Devotion Aura",
        position: "a2",
        icon: "/talents/icons/paladin/spell_holy_devotionaura.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Redoubt: {
        id: 20127,
        name: "Redoubt",
        position: "a3",
        icon: "/talents/icons/paladin/ability_defend.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Precision: {
        id: 20189,
        name: "Precision",
        position: "b1",
        icon: "/talents/icons/paladin/ability_rogue_ambush.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Guardian's Favor": {
        id: 20174,
        name: "Guardian's Favor",
        position: "b2",
        icon: "/talents/icons/paladin/spell_holy_sealofprotection.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      Toughness: {
        id: 20143,
        name: "Toughness",
        position: "b4",
        icon: "/talents/icons/paladin/spell_holy_devotionaura.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Blessing of Kings": {
        id: 20217,
        name: "Blessing of Kings",
        position: "c1",
        icon: "/talents/icons/paladin/spell_magic_magearmor.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Improved Righteous Fury": {
        id: 20468,
        name: "Improved Righteous Fury",
        position: "c2",
        icon: "/talents/icons/paladin/spell_holy_sealoffury.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Sheild Specialization": {
        id: 20148,
        name: "Sheild Specialization",
        position: "c3",
        icon: "/talents/icons/paladin/inv_shield_06.jpg",
        maxRank: 3,
        reqPoints: 10,
        arrows: [{ dir: "down", from: "a3", to: "c3" }],
      },
      Anticipation: {
        id: 20096,
        name: "Anticipation",
        position: "c4",
        icon: "/talents/icons/paladin/spell_magic_lesserinvisibilty.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Improved Hammer of Justice": {
        id: 20487,
        name: "Improved Hammer of Justice",
        position: "d2",
        icon: "/talents/icons/paladin/spell_holy_sealofmight.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Improved Concentration Aura": {
        id: 20254,
        name: "Improved Concentration Aura",
        position: "d3",
        icon: "/talents/icons/paladin/spell_holy_mindsooth.jpg",
        maxRank: 3,
        reqPoints: 15,
      },
      "Blessing of Sanctuary": {
        id: 20911,
        name: "Blessing of Sanctuary",
        position: "e2",
        icon: "/talents/icons/paladin/spell_nature_lightningshield.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      Reckoning: {
        id: 20177,
        name: "Reckoning",
        position: "e3",
        icon: "/talents/icons/paladin/spell_holy_blessingofstrength.jpg",
        maxRank: 5,
        reqPoints: 20,
      },
      "One-Handed Weapon Specialization": {
        id: 20196,
        name: "One-Handed Weapon Specialization",
        position: "f3",
        icon: "/talents/icons/paladin/inv_sword_20.jpg",
        maxRank: 5,
        reqPoints: 25,
      },
      "Holy Shield": {
        id: 20925,
        name: "Holy Shield",
        position: "g2",
        icon: "/talents/icons/paladin/classic_spell_holy_blessingofprotection.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
    },
  },
  Retribution: {
    name: "Retribution",
    background: "/talents/tree-backgrounds/paladin/retribution.jpg",
    icon: "/talents/icons/paladin/spell_holy_auraoflight.jpg",
    talents: {
      "Improved Blessing of Might": {
        id: 20042,
        name: "Improved Blessing of Might",
        position: "a2",
        icon: "/talents/icons/paladin/spell_holy_fistofjustice.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      Benediction: {
        id: 20101,
        name: "Benediction",
        position: "a3",
        icon: "/talents/icons/paladin/spell_frost_windwalkon.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Judgement": {
        id: 25956,
        name: "Improved Judgement",
        position: "b1",
        icon: "/talents/icons/paladin/spell_holy_righteousfury.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Seal of the Crusader": {
        id: 20335,
        name: "Improved Seal of the Crusader",
        position: "b2",
        icon: "/talents/icons/paladin/spell_holy_holysmite.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      Deflection: {
        id: 20060,
        name: "Deflection",
        position: "b3",
        icon: "/talents/icons/paladin/ability_parry.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      Vindication: {
        id: 9452,
        name: "Vindication",
        position: "c1",
        icon: "/talents/icons/paladin/spell_holy_vindication.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      Conviction: {
        id: 20117,
        name: "Conviction",
        position: "c2",
        icon: "/talents/icons/paladin/spell_holy_retributionaura.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Seal of Command": {
        id: 20375,
        name: "Seal of Command",
        position: "c3",
        icon: "/talents/icons/paladin/ability_warrior_innerrage.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Pursuit of Justice": {
        id: 26022,
        name: "Pursuit of Justice",
        position: "c4",
        icon: "/talents/icons/paladin/spell_holy_persuitofjustice.jpg",
        maxRank: 2,
        reqPoints: 10,
      },
      "Eye for an Eye": {
        id: 9799,
        name: "Eye for an Eye",
        position: "d1",
        icon: "/talents/icons/paladin/spell_holy_eyeforaneye.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Improved Retribution Aura": {
        id: 20091,
        name: "Improved Retribution Aura",
        position: "d3",
        icon: "/talents/icons/paladin/spell_holy_auraoflight.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Two-Handed Weapon Specialization": {
        id: 20111,
        name: "Two-Handed Weapon Specialization",
        position: "e1",
        icon: "/talents/icons/paladin/inv_hammer_04.jpg",
        maxRank: 3,
        reqPoints: 20,
      },
      "Sanctity Aura": {
        id: 20218,
        name: "Sanctity Aura",
        position: "e3",
        icon: "/talents/icons/paladin/spell_holy_mindvision.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      Vengence: {
        id: 20049,
        name: "Vengence",
        position: "f2",
        icon: "/talents/icons/paladin/ability_racial_avatar.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "c2", to: "f2" }],
      },
      Repentence: {
        id: 20066,
        name: "Repentence",
        position: "g2",
        icon: "/talents/icons/paladin/spell_holy_prayerofhealing.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
};
