import { TalentData } from "../util/types";

export const data: TalentData = {
  Affliction: {
    name: "Affliction",
    background: "/talents/tree-backgrounds/affliction.jpg",
    icon: "talents/icons/warlock/spell_shadow_deathcoil.jpg",
    talents: {
      Suppression: {
        name: "Suppression",
        position: "a2",
        icon: "talents/icons/warlock/spell_shadow_unsummonbuilding.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Corruption": {
        name: "Improved Corruption",
        position: "a3",
        icon: "talents/icons/warlock/spell_shadow_abominationexplosion.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Curse of Weakness": {
        name: "Improved Curse of Weakness",
        position: "b1",
        icon: "talents/icons/warlock/spell_shadow_curseofmannoroth.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Improved Drain Soul": {
        name: "Improved Drain Soul",
        position: "b2",
        icon: "talents/icons/warlock/spell_shadow_haunting.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Life Tap": {
        name: "Improved Life Tap",
        position: "b3",
        icon: "talents/icons/warlock/spell_shadow_burningspirit.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Drain Life": {
        name: "Improved Drain Life",
        position: "b4",
        icon: "talents/icons/warlock/spell_shadow_lifedrain02.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Improved Curse of Agony": {
        name: "Improved Curse of Agony",
        position: "c1",
        icon: "talents/icons/warlock/spell_shadow_curseofsargeras.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Fel Concentration": {
        name: "Fel Concentration",
        position: "c2",
        icon: "talents/icons/warlock/spell_shadow_fingerofdeath.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Amplify Curse": {
        name: "Amplify Curse",
        position: "c3",
        icon: "talents/icons/warlock/spell_shadow_contagion.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Grim Reach": {
        name: "Grim Reach",
        position: "d1",
        icon: "talents/icons/warlock/spell_shadow_callofbone.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      Nightfall: {
        name: "Nightfall",
        position: "d2",
        icon: "talents/icons/warlock/spell_shadow_twilight.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Improved Drain Mana": {
        name: "Improved Drain Mana",
        position: "d4",
        icon: "talents/icons/warlock/spell_shadow_siphonmana.jpg",
        maxRank: 2,
        reqPoints: 15,
      },
      "Siphon Life": {
        name: "Siphon Life",
        position: "e2",
        icon: "talents/icons/warlock/spell_shadow_requiem.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Curse of Exhaustion": {
        name: "Curse of Exhaustion",
        position: "e3",
        icon: "talents/icons/warlock/spell_shadow_grimward.jpg",
        maxRank: 1,
        reqPoints: 20,
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
      },
      "Improved Curse of Exhaustion": {
        name: "Improved Curse of Exhaustion",
        position: "e4",
        icon: "talents/icons/warlock/spell_shadow_grimward.jpg",
        maxRank: 4,
        reqPoints: 20,
        arrows: [{ dir: "right", from: "e3", to: "e4" }],
      },
      "Shadow Mastery": {
        name: "Shadow Mastery",
        position: "f2",
        icon: "talents/icons/warlock/spell_shadow_shadetruesight.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "e2", to: "f2" }],
      },
      "Dark Pact": {
        name: "Dark Pact",
        position: "g2",
        icon: "talents/icons/warlock/spell_shadow_darkritual.jpg",
        maxRank: 1,
        reqPoints: 30,
      },
    },
  },
  Demonology: {
    name: "Demonology",
    background: "/talents/tree-backgrounds/demonology.jpg",
    icon: "talents/icons/warlock/spell_shadow_metamorphosis.jpg",
    talents: {
      "Improved Healthstone": {
        name: "Improved Healthstone",
        position: "a1",
        icon: "talents/icons/warlock/inv_stone_04.jpg", // "spell_shadow_lifedrain
        maxRank: 2,
        reqPoints: 0,
      },
      "Improved Imp": {
        name: "Improved Imp",
        position: "a2",
        icon: "talents/icons/warlock/spell_shadow_summonimp.jpg",
        maxRank: 3,
        reqPoints: 0,
      },
      "Demonic Embrace": {
        name: "Demonic Embrace",
        position: "a3",
        icon: "talents/icons/warlock/spell_shadow_metamorphosis.jpg",
        maxRank: 5,
        reqPoints: 0,
      },
      "Improved Health Funnel": {
        name: "Improved Health Funnel",
        position: "b1",
        icon: "talents/icons/warlock/spell_shadow_lifedrain.jpg",
        maxRank: 2,
        reqPoints: 5,
      },
      "Improved Voidwalker": {
        name: "Improved Voidwalker",
        position: "b2",
        icon: "talents/icons/warlock/spell_shadow_summonvoidwalker.jpg",
        maxRank: 3,
        reqPoints: 5,
      },
      "Fel Intellect": {
        name: "Fel Intellect",
        position: "b3",
        icon: "talents/icons/warlock/spell_holy_magicalsentry.jpg",
        maxRank: 5,
        reqPoints: 5,
      },
      "Improved Succubus": {
        name: "Improved Succubus",
        position: "c1",
        icon: "talents/icons/warlock/spell_shadow_summonsuccubus.jpg",
        maxRank: 3,
        reqPoints: 10,
      },
      "Fel Domination": {
        name: "Fel Domination",
        position: "c2",
        icon: "talents/icons/warlock/spell_nature_removecurse.jpg",
        maxRank: 1,
        reqPoints: 10,
      },
      "Fel Stamina": {
        name: "Fel Stamina",
        position: "c3",
        icon: "talents/icons/warlock/spell_shadow_antishadow.jpg",
        maxRank: 5,
        reqPoints: 10,
      },
      "Master Summoner": {
        name: "Master Summoner",
        position: "d2",
        icon: "talents/icons/warlock/spell_shadow_impphaseshift.jpg",
        maxRank: 2,
        reqPoints: 15,
        arrows: [{ dir: "down", from: "c2", to: "d2" }],
      },
      "Unholy Power": {
        name: "Unholy Power",
        position: "d3",
        icon: "talents/icons/warlock/spell_shadow_shadowworddominate.jpg",
        maxRank: 5,
        reqPoints: 15,
      },
      "Improved Enslave Demon": {
        name: "Improved Enslave Demon",
        position: "e1",
        icon: "talents/icons/warlock/spell_shadow_enslavedemon.jpg",
        maxRank: 5,
        reqPoints: 20,
      },
      "Demonic Sacrifice": {
        name: "Demonic Sacrifice",
        position: "e2",
        icon: "talents/icons/warlock/spell_shadow_psychicscream.jpg",
        maxRank: 1,
        reqPoints: 20,
      },
      "Improved Firestone": {
        name: "Improved Firestone",
        position: "e4",
        icon: "talents/icons/warlock/inv_ammo_firetar.jpg",
        maxRank: 2,
        reqPoints: 20,
      },
      "Master Demonologist": {
        name: "Master Demonologist",
        position: "f3",
        icon: "talents/icons/warlock/spell_shadow_shadowpact.jpg",
        maxRank: 5,
        reqPoints: 25,
        arrows: [{ dir: "down", from: "d3", to: "f3" }],
      },
      "Soul Link": {
        name: "Soul Link",
        position: "g2",
        icon: "talents/icons/warlock/spell_shadow_gathershadows.jpg",
        maxRank: 1,
        reqPoints: 30,
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
      },
      "Improved Spellstone": {
        name: "Improved Spellstone",
        position: "g3",
        icon: "talents/icons/warlock/inv_misc_gem_sapphire_01.jpg",
        maxRank: 2,
        reqPoints: 30,
      },
    },
  },
  Destruction: {
    name: "Destruction",
    background: "/talents/tree-backgrounds/destruction.jpg",
    icon: "talents/icons/warlock/spell_shadow_rainoffire.jpg",
    talents: {
      "Improved Shadow Bolt": {
        name: "Improved Shadow Bolt",
        position: "a2",
        icon: icons["spell_shadow_shadowbolt"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by ${[
          4, 8, 12, 16, 20,
        ]}% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.`,
      },
      Cataclysm: {
        name: "Cataclysm",
        position: "a3",
        icon: icons["spell_fire_windsofwoe"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the Mana cost of your Destruction spells by ${[
          1, 2, 3, 4, 5,
        ]}%.`,
      },
      Bane: {
        name: "Bane",
        position: "b2",
        icon: icons["spell_shadow_deathpact"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the casting time of your Shadow Bolt and Immolate spells by ${[
          0.1, 0.2, 0.3, 0.4, 0.5,
        ]} sec and your Soul Fire spell by ${[0.4, 0.8, 1.2, 1.6, 2]} sec.`,
      },
      Aftermath: {
        name: "Aftermath",
        position: "b3",
        icon: icons["spell_fire_fire"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives your Destruction spells a ${[
          2, 4, 6, 8, 10,
        ]}% chance to daze the target for 5 sec.`,
      },
      "Improved Firebolt": {
        name: "Improved Firebolt",
        position: "c1",
        icon: icons["spell_fire_firebolt"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Reduces the casting time of your Imp's Firebolt spell by ${[
          0.5, 1,
        ]} sec.`,
      },
      "Improved Lash of Pain": {
        name: "Improved Lash of Pain",
        position: "c2",
        icon: icons["spell_shadow_curse"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Reduces the cooldown of your Succubus' Lash of Pain by ${[
          3, 6,
        ]} sec.`,
      },
      Devastation: {
        name: "Devastation",
        position: "c3",
        icon: icons["spell_fire_flameshock"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the critical strike chance of your Destruction spells by ${[
          1, 2, 3, 4, 5,
        ]}%.`,
      },
      Shadowburn: {
        name: "Shadowburn",
        position: "c4",
        icon: icons["spell_shadow_scourgebuild"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Instantly blasts the target for 91 to 104 Shadow damage. If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard.`,
      },
      Intensity: {
        name: "Intensity",
        position: "d1",
        icon: icons["spell_fire_lavaspawn"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          35, 70,
        ]}% chance to resist interruption caused by damage while channeling the Rain of Fire, Hellfire or Soul Fire spell.`,
      },
      "Destructive Reach": {
        name: "Destructive Reach",
        position: "d2",
        icon: icons["spell_shadow_corpseexplode"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Increases the range of your Destruction spells by ${[
          10, 20,
        ]}%.`,
      },
      "Improved Searing Pain": {
        name: "Improved Searing Pain",
        position: "d4",
        icon: icons["spell_fire_soulburn"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases the critical strike chance of your Searing Pain spell by ${[
          2, 4, 6, 8, 10,
        ]}%.`,
      },
      Pyroclasm: {
        name: "Pyroclasm",
        position: "e1",
        icon: icons["spell_fire_volcano"],
        maxRank: 2,
        reqPoints: 20,
        prereq: "Intensity",
        arrows: [{ dir: "down", from: "d1", to: "e1" }],
        description: talentText`Gives your Rain of Fire, Hellfire, and Soul Fire spells a ${[
          13, 26,
        ]}% chance to stun the target for 3 sec.`,
      },
      "Improved Immolate": {
        name: "Improved Immolate",
        position: "e2",
        icon: icons["spell_fire_immolation"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increases the initial damage of your Immolate spell by ${[
          5, 10, 15, 20, 25,
        ]}%.`,
      },
      Ruin: {
        name: "Ruin",
        position: "e3",
        icon: icons["spell_shadow_shadowwordpain"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Devastation",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`Increases the critical strike damage bonus of your Destruction spells by 100%.`,
      },
      Emberstorm: {
        name: "Emberstorm",
        position: "f3",
        icon: icons["spell_fire_selfdestruct"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage done by your Fire spells by ${[
          2, 4, 6, 8, 10,
        ]}%.`,
      },
      Conflagrate: {
        name: "Conflagrate",
        position: "g2",
        icon: icons["spell_fire_fireball"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Improved Immolate",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Ignites a target that is already afflicted by Immolate, dealing 249 to 316 Fire damage and consuming the Immolate spell.`,
      },
    },
  },
};
